all:
  hosts:
    endeus-stag-k8s-master-1:
      ansible_host: 192.168.16.220
      ip: 192.168.16.220
      access_ip: 192.168.16.220
    endeus-stag-k8s-master-2:
      ansible_host: 192.168.16.221
      ip: 192.168.16.221
      access_ip: 192.168.16.221
    endeus-stag-k8s-master-3:
      ansible_host: 192.168.16.222
      ip: 192.168.16.222
      access_ip: 192.168.16.222
    endeus-stag-k8s-worker-1:
      ansible_host: 192.168.16.213
      ip: 192.168.16.213
      access_ip: 192.168.16.213
    endeus-stag-k8s-worker-2:
      ansible_host: 192.168.16.214
      ip: 192.168.16.214
      access_ip: 192.168.16.214
    endeus-stag-k8s-worker-3:
      ansible_host: 192.168.16.215
      ip: 192.168.16.215
      access_ip: 192.168.16.215
  children:
    kube_control_plane:
      hosts:
        endeus-stag-k8s-master-1:
        endeus-stag-k8s-master-2:
        endeus-stag-k8s-master-3:
    kube_node:
      hosts:
        endeus-stag-k8s-worker-1:
        endeus-stag-k8s-worker-2:
        endeus-stag-k8s-worker-3:
    etcd:
      hosts:
        endeus-stag-k8s-master-1:
        endeus-stag-k8s-master-2:
        endeus-stag-k8s-master-3:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
